# Automatically generated by: ros2nix --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-cmake-python,
  ament-lint-auto,
  ament-lint-common,
  lifecycle-msgs,
  rclcpp,
  rclcpp-lifecycle,
  rclpy,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-virtual-driver";
  version = "0.1.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    ament-cmake-python
    rosidl-default-generators
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    lifecycle-msgs
    rclcpp
    rclcpp-lifecycle
    rclpy
    rosidl-default-runtime
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python
    rosidl-default-generators
  ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ asl20 ];
  };
}
