# Automatically generated by: ros2nix --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  nav-msgs,
  tf2,
  tf2-ros,
  virtual-driver,
}:
buildRosPackage rec {
  pname = "ros-jazzy-sdrive";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    nav-msgs
    tf2
    tf2-ros
    virtual-driver
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ asl20 ];
  };
}
